POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imd1ZCIsImlkIjoiNjEwYWEwZDA1MjY0MTAyMTY2MzVlNmQ1IiwiaWF0IjoxNjI4MDk3MjY5fQ.rpi3t_brQXg9toKxXDc4QGQwD9UfgBeSlsjFcMAtrjk

{
    "title": "post69",
    "url": "dsfdsfasdf",
    "likes": 4565,
    "userId": "610aa0d0526410216635e6d5"
}